# Generated by Django 5.1.6 on 2025-03-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='votes',
            new_name='likes',
        ),
    ]
