# Generated by Django 5.1.6 on 2025-03-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='comment_uploads/%Y/%m/%d/'),
        ),
    ]
